const assert = require('node:assert/strict');
const { defaultCustomTheme, tileColorIndex, validCustomTheme } = require('./custom');
const theme = defaultCustomTheme();
assert.equal(validCustomTheme(theme), true);
assert.equal(theme.tiles.length, 17);
assert.equal(2 ** theme.tiles.length, 131072);
assert.equal(2 ** (16 + 1), 131072);
assert.equal(tileColorIndex(11, true, 11), 0);
assert.equal(tileColorIndex(12, true, 11), 1);
assert.deepEqual(Array.from({length: 6}, (_, i) => tileColorIndex(i, true, 2)), [0,1,0,1,0,1]);
assert.equal(tileColorIndex(15, true, 1), 0);
assert.equal(tileColorIndex(15, false, 11), 15);
for (const period of [0, 17, 1.5, NaN]) assert.throws(() => tileColorIndex(0, true, period), RangeError);
assert.equal(validCustomTheme({...theme, primary: 'red'}), false);
assert.equal(validCustomTheme({...theme, tiles: []}), false);
console.log('커스텀 기본값, 17개 색상, 반복 규칙 및 유효성 검사 통과');

assert.equal(tileColorIndex(16, false, 11), 16);
assert.equal(tileColorIndex(16, true, 16), 0);
const { randomizeUnlocked } = require('./custom');
const colors = {background:'#111111',text:'#222222'};
randomizeUnlocked(colors, ['background','text'], {'tile-0-background':true}, 'tile-0-', () => '#abcdef');
assert.deepEqual(colors, {background:'#111111',text:'#abcdef'});
const base = {primary:'#111111',scoreBox:'#222222'};
randomizeUnlocked(base, ['primary','scoreBox'], {primary:true,scoreBox:true}, '', () => '#abcdef');
assert.deepEqual(base, {primary:'#111111',scoreBox:'#222222'});
console.log('기본 색상 및 타일 색상 잠금 시 랜덤 제외 확인');
const darkDefault = defaultCustomTheme('dark');
assert.equal(darkDefault.baseTheme, 'dark');
assert.equal(darkDefault.background, '#1c1b19');
assert.equal(darkDefault.scoreBox, '#36322d');
assert.equal(darkDefault.tiles[0].background, '#635b4f');
assert.equal(validCustomTheme(darkDefault), true);
